spring.application.name=Shopping-Cart
spring.datasource.url=jdbc:mysql://localhost:3306/shopping_go
spring.datasource.username=root
spring.datasource.password=admin

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


spring.mail.host=smtp.gmail.com
spring.mail.username=sharmavanshabd@gmail.com
spring.mail.password=qqfctzfdoirinryw
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.debug=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
